build:
  test:
    image: abakpress/dind-testing
    pull: true
    privileged: true
    volumes:
      - /home/data/drone/images:/images
      - /home/data/drone/gems:/bundle
    environment:
      - COMPOSE_FILE_EXT=drone
    commands:
      - wrapdocker docker -v

      - fetch-images
        --image whilp/ssh-agent
        --image abakpress/ruby-app:$RUBY_IMAGE_TAG

      - dip ssh add -T
      - dip provision
      - dip rspec

  release:
    image: abakpress/gem-publication:latest
    pull: true
    when:
      branch: master
      event: push
    commands:
      - release-gem
